export const argtypes = {
    flag: { control: { type: 'boolean' } },
    object: { control: { type: 'object' } },
    text: { control: { type: 'text' } },
    color: { control: { type: 'color' } },
    classes: { table: { disable: true } },
    closable: { control: { type: 'boolean' } },
    number: { control: { type: 'number' } },
    description: { control: { type: 'text' } },
    _disabled: { table: { disable: true } },
    disabled: { control: { type: 'boolean' } },
    image: { control: { type: 'object' } },
    label: { control: { type: 'text' } },
    logo: { control: { type: 'object' } },
    message: { control: { type: 'text' } },
    name: { control: { type: 'text' } },
    onChange: { table: { disable: true } },
    onClick: { table: { disable: true } },
    onClose: { table: { disable: true } },
    opened: { control: { type: 'boolean' } },
    overline: { control: { type: 'text' } },
    placeholder: { control: { type: 'text' } },
    alignment: { control: { type: 'select' }, options: ['left', 'center', 'right'] },
    progress: { control: { type: 'number' } },
    quantity: { control: { type: 'number' } },
    rating: { control: { type: 'number' } },
    corner: { control: { type: 'select' }, options: ['top-left', 'top-right', 'bottom-left', 'bottom-right'] },
    size: { control: { type: 'select' }, options: ['xs', 'sm', 'md', 'lg', 'xl'] },
    subtitle: { control: { type: 'text' } },
    title: { control: { type: 'text' } },
    helper: { control: { type: 'text' } },
};

export default argtypes;
