import clsxm from './clsxm';
import { clsxm_params } from '../types';

export const styles = {
    common: {
        'filled-primary': 'bg-clear',
        'filled-secondary': 'bg-clear',
        'filled-success': 'bg-clear',
        'filled-info': 'bg-clear',
        'filled-warning': 'bg-clear',
        'filled-danger': 'bg-clear',
        'filled-disabled': 'bg-clear',
        'filled-light': 'bg-clear',
        'filled-dark': 'bg-clear',
        'filled-none': 'bg-clear',
        'outlined-primary': 'bg-transparent',
        'outlined-secondary': 'bg-transparent',
        'outlined-success': 'bg-transparent',
        'outlined-info': 'bg-transparent',
        'outlined-warning': 'bg-transparent',
        'outlined-danger': 'bg-transparent',
        'outlined-disabled': 'bg-transparent',
        'outlined-light': 'bg-transparent',
        'outlined-dark': 'bg-transparent',
        'outlined-none': 'bg-transparent',
        'contained-primary': 'bg-primary',
        'contained-secondary': 'bg-secondary',
        'contained-success': 'bg-success',
        'contained-info': 'bg-info',
        'contained-warning': 'bg-warning',
        'contained-danger': 'bg-danger',
        'contained-disabled': 'bg-disabled',
        'contained-light': 'bg-light',
        'contained-dark': 'bg-dark',
        'contained-none': 'bg-clear',
        'light-primary': 'bg-clear',
        'light-secondary': 'bg-clear',
        'light-success': 'bg-clear',
        'light-info': 'bg-clear',
        'light-warning': 'bg-clear',
        'light-danger': 'bg-clear',
        'light-disabled': 'bg-clear',
        'light-light': 'bg-clear',
        'light-dark': 'bg-clear',
        'light-none': 'bg-clear',
    },
    nonDisabledStyles: {
        'filled-primary': 'focus:outline-none',
        'filled-secondary': 'focus:outline-none',
        'filled-success': 'focus:outline-none',
        'filled-info': 'focus:outline-none',
        'filled-warning': 'focus:outline-none',
        'filled-danger': 'focus:outline-none',
        'filled-disabled': 'focus:outline-none',
        'filled-light': 'focus:outline-none',
        'filled-dark': 'focus:outline-none',
        'filled-none': 'bg-clear focus:outline-none',
        'outlined-primary': 'focus:outline-none',
        'outlined-secondary': 'focus:outline-none',
        'outlined-success': 'focus:outline-none',
        'outlined-info': 'focus:outline-none',
        'outlined-warning': 'focus:outline-none',
        'outlined-danger': 'focus:outline-none',
        'outlined-disabled': 'focus:outline-none',
        'outlined-light': 'focus:outline-none',
        'outlined-dark': 'focus:outline-none',
        'outlined-none': 'bg-clear focus:outline-none',
        'contained-primary': 'focus:outline-none',
        'contained-secondary': 'focus:outline-none',
        'contained-success': 'focus:outline-none',
        'contained-info': 'focus:outline-none',
        'contained-warning': 'focus:outline-none',
        'contained-danger': 'focus:outline-none',
        'contained-disabled': 'focus:outline-none',
        'contained-light': 'focus:outline-none',
        'contained-dark': 'focus:outline-none',
        'contained-none': 'bg-clear focus:outline-none',
        'light-primary': 'focus:outline-none',
        'light-secondary': 'focus:outline-none',
        'light-success': 'focus:outline-none',
        'light-info': 'focus:outline-none',
        'light-warning': 'focus:outline-none',
        'light-danger': 'focus:outline-none',
        'light-disabled': 'focus:outline-none',
        'light-light': 'focus:outline-none',
        'light-dark': 'focus:outline-none',
        'light-none': 'bg-clear focus:outline-none',
    },
    hoverable: {
        'filled-primary': 'hover:bg-primary hover:bg-opacity-20',
        'filled-secondary': 'hover:bg-secondary hover:bg-opacity-20',
        'filled-success': 'hover:bg-success hover:bg-opacity-20',
        'filled-info': 'hover:bg-info hover:bg-opacity-20',
        'filled-warning': 'hover:bg-warning hover:bg-opacity-20',
        'filled-danger': 'hover:bg-danger hover:bg-opacity-20',
        'filled-disabled': 'hover:bg-disabled',
        'filled-light': 'hover:bg-light',
        'filled-dark': 'hover:bg-dark hover:bg-opacity-20',
        'filled-none': '',
        'outlined-primary': 'hover:bg-primary',
        'outlined-secondary': 'hover:bg-secondary',
        'outlined-success': 'hover:bg-success',
        'outlined-info': 'hover:bg-info',
        'outlined-warning': 'hover:bg-warning',
        'outlined-danger': 'hover:bg-danger',
        'outlined-disabled': 'hover:bg-disabled',
        'outlined-light': 'hover:bg-light',
        'outlined-dark': 'hover:bg-dark',
        'outlined-none': '',
        'contained-primary': 'hover:bg-opacity-70',
        'contained-secondary': 'hover:bg-opacity-70',
        'contained-success': 'hover:bg-opacity-70',
        'contained-info': 'hover:bg-opacity-70',
        'contained-warning': 'hover:bg-opacity-70',
        'contained-danger': 'hover:bg-opacity-70',
        'contained-disabled': 'hover:bg-opacity-50',
        'contained-light': 'hover:bg-opacity-50',
        'contained-dark': 'hover:bg-opacity-70',
        'contained-none': '',
        'light-primary': 'hover:bg-primary hover:bg-opacity-20',
        'light-secondary': 'hover:bg-secondary hover:bg-opacity-5',
        'light-success': 'hover:bg-success hover:bg-opacity-5',
        'light-info': 'hover:bg-info hover:bg-opacity-5',
        'light-warning': 'hover:bg-warning hover:bg-opacity-5',
        'light-danger': 'hover:bg-danger hover:bg-opacity-5',
        'light-disabled': 'hover:bg-disabled hover:bg-opacity-5',
        'light-light': 'hover:bg-light hover:bg-opacity-5',
        'light-dark': 'hover:bg-dark hover:bg-opacity-5',
        'light-none': 'hover:bg-none hover:bg-opacity-5',
    },
};

export const bgClass = (params: clsxm_params) => clsxm(params, styles);

export default bgClass;
