import clsxm, {clsxm_params} from "./clsxm";

export const styles = {
    common: {
        'filled-primary': '',
        'filled-secondary': '',
        'filled-success': '',
        'filled-info': '',
        'filled-warning': '',
        'filled-danger': '',
        'filled-light': '',
        'filled-dark': '',
        'filled-none': 'bg-white',
        'outlined-primary': 'bg-transparent',
        'outlined-secondary': 'bg-transparent',
        'outlined-success': 'bg-transparent',
        'outlined-info': 'bg-transparent',
        'outlined-warning': 'bg-transparent',
        'outlined-danger': 'bg-transparent',
        'outlined-light': 'bg-transparent',
        'outlined-dark': 'bg-transparent',
        'outlined-none': 'bg-white',
        'contained-primary': 'bg-primary',
        'contained-secondary': 'bg-secondary',
        'contained-success': 'bg-success',
        'contained-info': 'bg-info',
        'contained-warning': 'bg-warning',
        'contained-danger': 'bg-danger',
        'contained-light': 'bg-light',
        'contained-dark': 'bg-dark',
        'contained-none': 'bg-white',
    },
    nonDisabledStyles: {
        'filled-primary': 'focus:outline-none',
        'filled-secondary': 'focus:outline-none',
        'filled-success': 'focus:outline-none',
        'filled-info': 'focus:outline-none',
        'filled-warning': 'focus:outline-none',
        'filled-danger': 'focus:outline-none',
        'filled-light': 'focus:outline-none',
        'filled-dark': 'focus:outline-none',
        'filled-none': 'bg-white focus:outline-none',
        'outlined-primary': 'focus:outline-none',
        'outlined-secondary': 'focus:outline-none',
        'outlined-success': 'focus:outline-none',
        'outlined-info': 'focus:outline-none',
        'outlined-warning': 'focus:outline-none',
        'outlined-danger': 'focus:outline-none',
        'outlined-light': 'focus:outline-none',
        'outlined-dark': 'focus:outline-none',
        'outlined-none': 'bg-white focus:outline-none',
        'contained-primary': 'focus:outline-none',
        'contained-secondary': 'focus:outline-none',
        'contained-success': 'focus:outline-none',
        'contained-info': 'focus:outline-none',
        'contained-warning': 'focus:outline-none',
        'contained-danger': 'focus:outline-none',
        'contained-light': 'focus:outline-none',
        'contained-dark': 'focus:outline-none',
        'contained-none': 'bg-white focus:outline-none',
    },
    hoverable: {
        'filled-primary': 'hover:bg-primary hover:bg-opacity-20',
        'filled-secondary': 'hover:bg-secondary hover:bg-opacity-20',
        'filled-success': 'hover:bg-success hover:bg-opacity-20',
        'filled-info': 'hover:bg-info hover:bg-opacity-20',
        'filled-warning': 'hover:bg-warning hover:bg-opacity-20',
        'filled-danger': 'hover:bg-danger hover:bg-opacity-20',
        'filled-light': 'hover:bg-light',
        'filled-dark': 'hover:bg-dark hover:bg-opacity-20',
        'filled-none': '',
        'outlined-primary': 'hover:bg-primary',
        'outlined-secondary': 'hover:bg-secondary',
        'outlined-success': 'hover:bg-success',
        'outlined-info': 'hover:bg-info',
        'outlined-warning': 'hover:bg-warning',
        'outlined-danger': 'hover:bg-danger',
        'outlined-light': 'hover:bg-light',
        'outlined-dark': 'hover:bg-dark',
        'outlined-none': '',
        'contained-primary': 'hover:bg-opacity-70',
        'contained-secondary': 'hover:bg-opacity-70',
        'contained-success': 'hover:bg-opacity-70',
        'contained-info': 'hover:bg-opacity-70',
        'contained-warning': 'hover:bg-opacity-70',
        'contained-danger': 'hover:bg-opacity-70',
        'contained-light': 'hover:bg-opacity-50',
        'contained-dark': 'hover:bg-opacity-70',
        'contained-none': '',
    },
};

export const bgClass = (params: clsxm_params) => clsxm(params, styles);

export default bgClass