import clsxm from './clsxm';
import { clsxm_params } from '../types';

export const styles = {
    common: {
        'filled-primary': '',
        'filled-secondary': '',
        'filled-success': '',
        'filled-info': '',
        'filled-warning': '',
        'filled-danger': '',
        'filled-light': '',
        'filled-dark': '',
        'filled-none': '',
        'outlined-primary': 'border border-primary',
        'outlined-secondary': 'border border-secondary',
        'outlined-success': 'border border-success',
        'outlined-info': 'border border-info',
        'outlined-warning': 'border border-warning',
        'outlined-danger': 'border border-danger',
        'outlined-light': 'border border-light',
        'outlined-dark': 'border border-dark',
        'outlined-none': '',
        'contained-primary': '',
        'contained-secondary': '',
        'contained-success': '',
        'contained-info': '',
        'contained-warning': '',
        'contained-danger': '',
        'contained-light': '',
        'contained-dark': '',
        'contained-none': '',
    },
    nonDisabled: {
        'filled-primary': '',
        'filled-secondary': '',
        'filled-success': '',
        'filled-info': '',
        'filled-warning': '',
        'filled-danger': '',
        'filled-light': '',
        'filled-dark': '',
        'filled-none': '',
        'outlined-primary': '',
        'outlined-secondary': '',
        'outlined-success': '',
        'outlined-info': '',
        'outlined-warning': '',
        'outlined-danger': '',
        'outlined-light': '',
        'outlined-dark': '',
        'outlined-none': '',
        'contained-primary': '',
        'contained-secondary': '',
        'contained-success': '',
        'contained-info': '',
        'contained-warning': '',
        'contained-danger': '',
        'contained-light': '',
        'contained-dark': '',
        'contained-none': '',
    },
    hoverable: {
        'filled-primary': '',
        'filled-secondary': '',
        'filled-success': '',
        'filled-info': '',
        'filled-warning': '',
        'filled-danger': '',
        'filled-light': '',
        'filled-dark': '',
        'filled-none': '',
        'outlined-primary': 'hover:border-transparent',
        'outlined-secondary': 'hover:border-transparent',
        'outlined-success': 'hover:border-transparent',
        'outlined-info': 'hover:border-transparent',
        'outlined-warning': 'hover:border-transparent',
        'outlined-danger': 'hover:border-transparent',
        'outlined-light': 'hover:border-transparent',
        'outlined-dark': 'hover:border-transparent',
        'outlined-none': '',
        'contained-primary': '',
        'contained-secondary': '',
        'contained-success': '',
        'contained-info': '',
        'contained-warning': '',
        'contained-danger': '',
        'contained-light': '',
        'contained-dark': '',
        'contained-none': '',
    },
};

export const borderClass = (params: clsxm_params) => clsxm(params, styles);

export default borderClass;
